version: '3.7'
services:
  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass redis
    volumes:
      - ./.cache/redis:/data
    ports:
      - '6379:6379'

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./.cache/postgres:/var/lib/postgresql/data
